alias: Alert City Hunter
description: Alert City Hunter
trigger:
  - platform: template
    value_template: >-
      {{ 'City Hunter' in
      state_attr('sensor.ora_e_dopo_in_tv_italia_2','nexttitle') }}
condition: []
action:
  - device_id: XXXXXXXXXXXXXXXX
    domain: mobile_app
    type: notify
    message: >-
      tra poco su Italia2 {{state_attr('sensor.ora_e_dopo_in_tv_italia_2',
      'nextdate_start') }}: {{state_attr('sensor.ora_e_dopo_in_tv_italia_2',
      'nextdescription') }}
    title: "{{state_attr('sensor.ora_e_dopo_in_tv_italia_2','nexttitle') }}"
    data:
      ttl: 0
      priority: high
      image: "{{state_attr('sensor.ora_e_dopo_in_tv_italia_2', 'nextcover') }}"
      actions:
        - action: CLOSE
          title: Segna come letto
mode: single
