alias: Update Palinsesto tv
description: Update Palinsesto tv
trigger:
  - platform: time_pattern
    minutes: /4
condition: []
action:
  - service: button.press
    metadata: {}
    data: {}
    target:
      entity_id:
        - button.update_ora_in_tv
        - button.ora_e_dopo_in_tv_update
mode: single
