alias: Update Palinsesto tv Domani
description: Update Palinsesto tv Domani
trigger:
  - platform: time_pattern
    minutes: "1"
    hours: "00"
condition: []
action:
  - service: button.press
    metadata: {}
    data: {}
    target:
      entity_id:
        - button.update_stasera_in_tv
        - button.update_domani_in_tv
mode: single
